k1LoW/runn

book.go
book_test.go
db.go
dump.go
dump_test.go
exec.go
http.go
include.go
operator.go
operator_test.go
option.go
test.go
testdata/book/github_map.yml
testdata/book/map.yml

Support following runbook
```yaml
desc: Login and get projects.
runners:
req: https://example.com/api/v1
db: mysql://root:mypass@localhost:3306/testdb
vars:
username: alice
steps:
db0:
db:
query: SELECT * FROM users WHERE name = '{{ vars.username }}'
req0:
req:
/login:
post:
body:
application/json:
email: "{{ steps.db1.rows[0].email }}"
password: "{{ steps.db1.rows[0].password }}"
test0:
test: steps.req0.res.status == 200
req1:
req:
/projects:
headers:
Authorization: "token {{ steps.req0.res.session_token }}"
get:
body: nil
test1:
test: steps.req1.res.status == 200
test2:
test: len(steps.req1.res.projects) > 0
```

Support named ( ordered map ) steps

---

bind.go
bind_test.go
operator.go

```yaml
steps:
- req: 
/users/k1low:
get:
body: null
- bind:
user_id: steps[0].res.body.data.id
- dump: user_id

Add bind runner for binding variables

---

operator.go
operator_test.go

The value to be expanded into an expression is determined to be a number, and single quotes are added to the path and GET parameters.
* Example
```yaml
vars:
year: 2022
steps:
-
req:
/api/path?year={{ vars.year }}:
get:
```
* Execution logs
```
-----START HTTP REQUEST-----
GET /api/path?year=%272022%27 HTTP/1.1
```
If the expanded content after executing string() is not only that expression, it seems better not to stringify it.
https://github.com/k1LoW/runn/pull/21

Fix support string expr

---

http_validator.go
http_validator_test.go

I want to validate HTTP requests with authentication.
Verification currently yields the following error.
```log
openapi3 validation error: Security requirements failed
```
Since checking the response code is sufficient to verify the authentication itself, you may want to set an option not to perform authentication checks when verifying the request.
NoopAuthenticationFunc was used.
see.
https://github.com/getkin/kin-openapi/blob/648d6b9a170b6162c79927aeba39bda2fe37386a/openapi3filter/validation_handler.go#L17-L18

Support OpenAPI3 validation at authentication request

---

operator.go
operator_test.go

If the value to be expanded into an expression is bool, an error will occur.
* Error example
```log
invalid format: true
```
It would be good to expand appropriately when the value is bool.

Support bool expand

---

book_test.go
go.mod
go.sum
testdata/book/env.yml

Allow default values to be specified when expanding environment variables in yaml.
* Example
```yml
desc: Example
debug: ${DEBUG:-true}
interval: ${INTERVAL:-5}
```
see.
https://github.com/k1LoW/expand/pull/4
* Bump up packages.
* Append test.

Support bash like interpolate 

---

http.go
http_test.go
testdata/openapi3.yml

When performing OAS Spec validation, the following error would occur in rare cases when submitting a request.
* example
```log
http request failed on ‘api test’.steps.oas: Put “http://localhost:8000/api/hoge/394336045384073216?date=202104”: http: ContentLength=591 with Body length 616
```
I couldn't reproduce it in the test code, but it looked like the request body object was being used all over again during validation.
Incidentally, the test scenario in which the problem occurred was reproducible, as it made extensive use of includes.
It seems to be stable if request doby is reset after verifying OAS Spec but before sending actual request.
Fixed an error in the response definition of the OAS Spec (Github API) that was found when creating the test code.

Improvement of unstable operation during OAS Spec verification

---

operator.go
operator_test.go

I want to make the struct defined in the vars section available as json in the request body
* yaml
```yml
desc: testing json request body
runners:
req:
endpoint: ${ENDPOINT:-https://httpbin.org/}
debug: ${DEBUG:-true}
vars:
jsonRequestBody:
foo: "test"
bar: 1
arrayJsonRequestBody:
-
foo: "test1"
bar: 1
-
foo: "test2"
bar: 2
steps:
-
req:
/post:
post:
body:
application/json: "{{ vars.jsonRequestBody }}"
-
test: |
steps[0].res.status == 200
-
req:
/put:
put:
body:
application/json: "{{ vars.arrayJsonRequestBody }}"
-
test: |
steps[2].res.status == 200
```
* Execution log
```log
Run 'req' on 'testing json request body'.steps[0]
-----START HTTP REQUEST-----
POST /post HTTP/1.1
Host: localhost
Content-Type: application/json
{"bar":1,"foo":"test"}
-----END HTTP REQUEST-----
-----START HTTP …
```

Support json object expand

---

.github/workflows/ci.yml
book.go
book_test.go
grpc.go
operator.go
operator_test.go
test.go
testdata/book/env.yml
testdata/book/httpbin.yml

There was a problem in which the type of the numerical value in the vars defined in yaml was different from the type of the numerical item in the response, causing the test to fail.
The reason is that the libraries used have different behavior when unmarshaling json and yaml.
* Verification Code
```go
package main
import (
"fmt"
"github.com/goccy/go-json"
"github.com/goccy/go-yaml"
"github.com/google/go-cmp/cmp"
)
func main() {
jb := []byte(`{"one": {"name": "alice", "age":30 }}`)
var ji map[string]interface{}
if err := json.Unmarshal(jb, &ji); err != nil {
panic(err)
}
yb := []byte(`
one:
name: "alice"
age: 30
`)
var yi map[string]interface{}
if err := yaml.Unmarshal(yb, &yi); err != nil {
panic(err)
}
if diff := cmp.Diff(ji, yi, nil); diff != "" {
fmt.Printf("%v", diff)
}
}
```
* …

Convert number var to json compatible type

---

testdata/book/httpbin.yml
testdata/book/httpbin_include.yml

refs https://github.com/k1LoW/runn/pull/97
- Ability to set loop counter from vars.
- Ability to use indexes in requests and tests in loop processing
- Ability to replace the retry process with a loop
- Ability to perform loop processing in combination with include
- To be retried when HTTP request times out
Error with `DeadlineExceeded`. May not have been handled originally
- The ability to refer to the results of an iterative process in a separate step.
- Ability to read external json using a loop counter.
#93 will be omitted from the response.

[TEST] loop: section

---

operator.go

Revert https://github.com/k1LoW/runn/blob/3dac4b040e56180cd1340deecf783523144642b5/operator.go#L133
In the Map syntax runbook, there is an error if a new step exists after a looped step.

Fix recordToMap

---

book.go
book_test.go
testdata/duplicate.yml

Should be an error if there are duplicate keys in the runbook in Map syntax.
```yaml
desc: Duplicate step keys
steps:
a:
test: true
b:
test: true
c:
test: true
a: # duplicate !!!
test: true
```

Error if duplicate step keys are found in the runbook in Map syntax.

---

README.md
go.mod
go.sum
operator.go
option.go

Add functions for casting as built-in functions to allow flexible use of values.
- `string` ... move internally configured as a built-in function
- `int` ... 🆕 
- `bool` ... 🆕

Add functions to cast as built-in functions

---

book.go

ref #103
I think TestShard is failing less often...

Stop creating anonymous structures in functions

---

option.go
testdata/book/httpbin.yml

Exclude some Entries when validating the response body so that it can be compared with vars.
* Example
```yml
-
desc: All the same except Content-Length
req:
/response-headers?freeform={{ vars.wantBody.freeform }}:
get:
body: null
test: |
steps[8].res.status == 200
&& compare(steps[8].res.body, vars.wantBody, "Content-Length")
```
* Define `go-cmp/cmp` compare functions as built-in functions
Is the selection of the library to be used reasonable?
* debug output is not optimized for syntax with functions
```
-----START TEST CONDITION-----
steps[8].res.status == 200
&& compare(steps[8].res.body, vars.wantBody, "Content-Length")
├── steps[8].res.status => 200
├── 200 => 200
├── compare(steps[8].res.body => ?
├── vars.wantBody => {"Content-Type":"application/json","freeform":"foo"}
├── …
```

Append compare function

---

operator.go
store.go
test.go
testdata/book/github.yml
testdata/book/github_map.yml

Fix https://github.com/k1LoW/runn/issues/113

Support `current` variable

---

operator.go
operator_test.go

Errors were occurring when trying to process uint64 during variable expansion.
```
invalid format: evaluated vars.uint64 , but got uint64(4600)
```
Let uint64 support.
I was able to verify this on a unit test level, but could not reproduce the error when run through RunBook.
I reproduced this when using the brew version, but I wonder if it has anything to do with it?

Support uint64 expand

---

db.go

fix https://github.com/k1LoW/runn/issues/124
* Isn't the DATETIME format different for different types of databases?
Can you identify the format from the DB connection driver?
No generic DateTime formatting library exists?
* What time zone should the date be in?
* How to implement the verification code?
* Support other formats besides DATETIME?
The following types exist, but they are all treated as numbers
DECIMAL, BOOL, INT, BIGINT

Support for DATETIME columns in DBRunner

---

book.go
capturer.go
capturer_test.go
db.go
db_test.go
exec.go
go.mod
go.sum
grpc.go
grpc_test.go
http.go
http_test.go
http_validator_test.go
include.go
operator.go
operator_test.go
option.go
test_test.go
testdata/book/http.yml
testdata/db.yml.debugger.golden
testdata/exec.yml.debugger.golden
testdata/grpc.yml.debugger.golden
testdata/http.yml.debugger.golden

ref: #116 
Introduce `type Capturer interface` to capture Runbook execution logs in various formats.
As a first step, reimplement Debug log using `type Capturer interface`.

Introduce `type Capturer interface`

---

book.go
book_test.go
cmd/list.go
db.go
db_test.go
grpc.go
grpc_test.go
http.go
http_test.go
operator.go
operator_test.go
option.go
option_test.go
testdata/book/env.yml

Currently, the initial parsing (yaml.Unmarshal) of the runbook is performed by operator{} and book{}, so we will centralize it in book{}.

Move the parsing operation of runbook(YAML) from operator{} to book{} to clarify responsibilities

---

book.go
operator_test.go
testdata/book/github_map.yml
yaml.go
yaml_test.go

Retry #147 #103 
Compatibility is ensured by a test that compares the output of `unmarshalAs*Steps()` and `unmarshalAs*Steps2()`.

Use gopkg.in/yaml.v2 only for the first YAML parsing to keep the parsing stable

---

eval.go
eval_test.go

ref: #123 
```yaml
test: |
current.res.status == 200
#This is comment
&& current.res.body.foo == vars.expectFoo
&& current.res.body.bar == vars.expectBar # This is NOT comment. TODO.
```

Support solo-single-line comment

---

eval.go
eval_test.go

ref: #123 
Support single-line comment with #176 
```yaml
test: |
current.res.status == 200
#This is comment
&& current.res.body.foo == vars.expectFoo
&& current.res.body.bar == vars.expectBar # This is comment!!!!!!
```

Support single-line comment

---

test.go
test_test.go

ref: https://github.com/k1LoW/runn/pull/180#issuecomment-1263707873
Fix the following incorrect displays
```
vars.tests[i] == vars.wants[i]
├──  => ?
└──  => ?
```

Fix buildTree()

---

builtin/compare.go
builtin/compare_test.go
builtin/time.go
builtin/time_test.go
option.go

migrate builtin functions to package

---

README.md
builtin/compare.go
builtin/diff.go
option.go
testdata/book/httpbin.yml
testdata/book/httpbin_include.yml

Append diff function

---

cmd/list.go
cmd/run.go
operator.go

Support `--skip-included` option for CLI ( `runn run` `runn list` ).
Instead, an error occurs if the runbook file is invalid.

[BREAKING] Support `--skip-included` option for CLI

---

book.go
cmd/new.go
cmd/root.go
cmd/run.go
operator.go
option.go
option_test.go

```console
$ runn new --grpc-no-tls --and-run -- grpcurl -d '{"greeting": "hello"}' grpcb.in:9000 hello.HelloService/SayHello
runners:
greq: grpc://grpcb.in:9000
steps:
- greq:
hello.HelloService/SayHello:
message:
greeting: hello
test: |
current.res.headers['content-type'][0] == "application/grpc"
&& compare(current.res.message, {"reply":"hello hello"})
&& current.res.status == 0
```
ref: https://grpcb.in/

Support `--grpc-no-tls` option for CLI and `GRPCNoTLS` option for test helper

---

go.mod
go.sum
runbook.go
runbook_test.go
testdata/axslog.append_step.golden

```console
$ cat access_log
10.0.0.11 - - [11/Jun/2017:05:56:04 +0900] "GET / HTTP/1.1" 200 741 "-" "mackerel-http-checker/0.0.1" "-"
10.0.0.11 - - [11/Jun/2017:06:56:04 +0900] "GET /path/to HTTP/1.1" 200 741 "-" "mackerel-http-checker/0.0.1" "-"
$ cat access_log | runn new
runners:
req: http://10.0.0.11
steps:
- req:
/:
get:
headers:
User-Agent: mackerel-http-checker/0.0.1
body: null
- req:
/path/to:
get:
headers:
User-Agent: mackerel-http-checker/0.0.1
body: null
$
```
Idea by @k2tzumi / [Parser](https://github.com/Songmu/axslogparser) by @Songmu
Thank you!!

Support create runbook from access log

---

cmd/new.go
runbook.go

```console
$ runn new --out http.yml -- curl https://httpbin.org/json -H "accept: application/json"
$ runn new --out http.yml -- curl https://httpbin.org/xml -H "accept: application/json"
$ cat http.yml
runners:
req: https://httpbin.org
steps:
- req:
/json:
get:
headers:
Accept: application/json
body: null
- req:
/xml:
get:
headers:
Accept: application/json
body: null
$
```

Support for appending steps via `runn new`

---

cmd/loadt.go
cmd/root.go
cmd/run.go
go.mod
go.sum
operator.go
operator_test.go

```console
$ runn loadt my.yml
Warm up time (--warm-up)....: 5s
Duration (--duration).......: 10s
Concurrent (--concurrent)...: 1
Total.......................: 892
Succeeded...................: 892
Failed......................: 0
Error rate..................: 0%
RunN per seconds............: 89.2
Latency ....................: max=30.3ms min=7.0ms avg=11.0ms med=9.8ms p(90)=16.3ms p(99)=25.4ms
$ runn loadt -h
run load test using runbooks.
Usage:
runn loadt [PATH_PATTERN] [flags]
Aliases:
loadt, loadtest
Flags:
--capture string     destination of runbook run capture results
--concurrent int     number of parallel load test runs (default 1)
--debug              debug
--duration string    load test running duration (default "10sec")
--fail-fast          fail fast
--grpc-no-tls        disable …
```

Add `runn loadt` for load test using runbooks

---

.github/workflows/tagpr.yml
Dockerfile.slim

```console
$ docker build . -t runn-test
$ docker container run -it --rm --name test -v $PWD/testdata/book:/books runn-test run books/pkg_go_dev.yml
Test using CDP ... ok
1 scenario, 0 skipped, 0 failures
```

Add Chrominium to Docker image for supporting CDP

---

README.md
go.mod
go.sum
option.go

ref: #296 
```console
$ cat prompt.yml
desc: Prompt
steps:
-
bind:
twitterID: input("Enter your twitter ID", "default")
-
dump: twitterID
$ go run ./cmd/runn/main.go run prompt.yml
Enter your twitter ID [default]: k1LoW
k1LoW
Prompt ... ok
1 scenario, 0 skipped, 0 failures
```

Add `input` `secret` `select` to built-in function for interactive input

---

http.go
yaml.go

Fix capture/runbook.go reading out request body when multipart/form-data

---

http_validator.go

Fix fatal error: concurrent map writes

openapi3filter.RegisterBodyDecoder only needs once.

---

debugger_test.go
operator.go
testdata/book/step_by_step_desc.yml
testdata/step_by_step_desc.yml.debugger.golden

Hello, thanks to great tool.
I've modified debug printing uses description for step if exists.
For example, there is a scenario file like below:
```yml
desc: 'A scenario file which has step by step desc'
steps:
-
desc: 'Print "hello world!!"'
exec:
command: echo hello world!!
-
desc: 'Print "hello world!!" again'
exec:
command: cat
stdin: '{{ steps[0].stdout }}'
-
desc: 'Check result of previous command contains "hello"'
test: 'steps[1].stdout contains "hello"'
```
Currently `runn --debug` prints like follows:
```console
Run 'exec' on 'Exec test'.steps[0] # <--- 🤔 
-----START COMMAND-----
echo hello world!!
-----END COMMAND-----
-----START STDOUT-----
hello world!!
-----END STDOUT-----
...
```
And now `runn --debug` prints debug info with step's description like follows:
```console
Run …
```

Prefer step desc if exist in debug printing

---

README.md
cmd/loadt.go
eval.go
eval_test.go
flags/flags.go

Fix #374 
```console
$ runn loadt --concurrent 2 --threshold 'error_rate < 20' path/to/*.yml
```

Add `--threshold` option for checking result of loadt

---

go.mod
go.sum
testdata/openapi3.yml

`getkin/kin-openapi` needs to be upgraded due to a problem with multipart request validation.
The following error occurs
https://github.com/k1LoW/runn/actions/runs/3977957064/jobs/6819452137#step:7:70
```
openapi3 validation error: request body has an error: failed to decode request body: part upload0: undefined
```
The above problem has been resolved in the following release
https://github.com/getkin/kin-openapi/releases/tag/v0.113.0

Bump up version of `getkin/kin-openapi`

---

operator.go
operator_test.go
testdata/book/failure_with_step_desc.yml

Currently, the step descriptions do not seem to be printed when a scenario fails.
I think this PR will be useful for identifying the step that caused the failure more quickly when the number of steps is large or the scenario has high complexity.
before: 
```console
$ runn run testdata/book/failure_with_step_desc.yml
Always failure scenario with step desc ... failed to run testdata/book/failure_with_step_desc.yml: test failed on 'Always failure scenario with step desc'.steps[0]: (false) is not true
false
└── false => false
1 scenario, 0 skipped, 1 failure
```
after:
```console
$ runn run testdata/book/failure_with_step_desc.yml 
Always failure scenario with step desc ... failed to run testdata/book/failure_with_step_desc.yml: test failed on 'Always failure scenario with step desc'.steps[0] …
```

Print step description on failure if available

---

go.mod
go.sum

refs https://github.com/getkin/kin-openapi/pull/755
Not officially released yet, but I'd like to version it up.

Bump up version of `kin-openapi` to `v0.113.1-0.20230128122015-6e233af317f2`

---

builtin/intersect.go
builtin/intersect_test.go
go.mod
go.sum
option.go
option_test.go

Background: https://github.com/k1LoW/runn/issues/409#issuecomment-1423742426
I have decided to return intersected array instead of boolean, because that would be more flexible. 
test.yaml
```yaml
desc: intersect
vars:
v1: [1, 2, 3]
v2: [2, 3, 4]
steps:
a:
test: 2 in intersect(vars.v1, vars.v2)
b:
test: 3 in intersect(vars.v1, vars.v2)
c:
test: 4 in intersect(vars.v1, vars.v2)
```
result
```
intersect ... failed to run intersect.yaml: test failed on 'intersect'.steps.c: (4 in intersect(vars.v1, vars.v2)) is not true
4 in intersect(vars.v1, vars.v2)
├── 4 => 4
├── intersect(vars.v1, vars.v2) => [2,3]
├── vars.v1 => [1,2,3]
└── vars.v2 => [2,3,4]
1 scenario, 0 skipped, 1 failure
```

Implement intersect function

---

.goreleaser.yml
Makefile

Some DEPRECATED messages were being output when running goreleaser.
https://github.com/k1LoW/runn/actions/runs/4149255449/jobs/7178039915#step:5:13
https://github.com/k1LoW/runn/actions/runs/4149255449/jobs/7178039915#step:5:20

Fixing goreleaser deprecated

---

book.go
include.go
include_test.go
option.go
testdata/book/use_parent_store_runners.yml
testdata/book/use_parent_store_vars.yml
vars.go

The values of `runners:` and `vars:` in the included runbook accept variables from the parent runbook.

---

README.md
book.go
go.mod
go.sum
operator.go
operator_test.go
option.go
runbook.go

Add `concurrency:` for ensuring that only a single runbook using the same group will run at a time.

---

option.go
option_test.go

`runn.GrpcRunner` 's options had nothing enabled.
So we made the function signature similar to SSHRunner/SSHRunnerWithOptions

Change function signature of GrpcRunner and Add GrpcRunnerWithOptions

---

README.md
book.go
include.go
operator.go
operator_test.go
option.go
parse.go
runbook.go
testdata/book/force.yml

Add an option to run to the last step even if the intermediate step fails.
If even one step fails, it is considered a failure as a runbook.

Support `force:` section to force all steps to run.

---

bind_test.go
operator_test.go
store.go
testdata/book/env.yml

`env` is different in variable expansion timing from `${ENV_NAME}`

Set environment variables to be extracted at each step in a variable as `env`.

---

http_validator.go
testdata/openapi3.yml

Revert "Fix logic to skip validation using `servers:` section in OpenAPI v3 spec"

---

operator.go
operator_test.go

Guarantee sequential run for each operator

---

cmd/list.go
flags/flags.go
operator.go

- Defaults to short trimmed ID, `--long` option to show the entire ID.
- `--long` option to show the full path.
```console
$ go run cmd/runn/main.go list testdata/book/*.yml | head
id:      desc:                                      if:       steps:  path
------------------------------------------------------------------------------------------------------------------
8150b83  Always failure scenario                                   3  t/b/always_failure.yml
8750a8e  Always success scenario                                   3  t/b/always_success.yml
fd8d83d  Login and get projects.                                   6  t/b/book.yml
b9f7be5  Test for json.*                                           3  t/b/builtin-json.yml
06c1f13  Test using CDP                                            6 …
```

Add show ids in `runn list` command

---

operator.go
operator_test.go
result.go
result_test.go
testdata/result_out_0.golden
testdata/result_out_1.golden
testdata/result_out_2.golden
testdata/result_out_json_0.golden
testdata/result_out_json_1.golden
testdata/result_out_json_2.golden

Set runnbook ID to result.
RunResult is not configured to save the results of steps included by Include runners, which needs to be corrected in the future.
```console
$ runn run *.yml
F
1) tmp.yml 6a5d63a3c2c505fbc67b941937ee79c16113fc0e
Failure/Error: test failed on 'Test desc'.steps.one 'Test desc one': (current.stdout == "Hello World") is not true
current.stdout == "Hello World"
├── current.stdout => "Hello World
│   "
└── "Hello World" => "Hello World"
1 scenario, 0 skipped, 1 failure
exit status 1
$ runn run *.yml --id 6a5d63
F
1) tmp.yml 6a5d63a3c2c505fbc67b941937ee79c16113fc0e
Failure/Error: test failed on 'Test desc'.steps.one 'Test desc one': (current.stdout == "Hello World") is not true
current.stdout == "Hello World"
├── current.stdout => "Hello World
│   "
└── "Hello World" => …
```

Set runnbook ID to result (STDOUT/JSON)

---

eval.go
eval_test.go

```console
$ go run cmd/runn/main.go run tmp.yml
F
1) tmp.yml 6a5d63a3c2c505fbc67b941937ee79c16113fc0e
Failure/Error: test failed on 'Test desc'.steps.one 'Test desc one': condition is not true
Condition:
current.stdout == "Hello World"
├── current.stdout => "Hello World
│   "
└── "Hello World" => "Hello World"
Failure step (tmp.yml):
3   one:
4     desc: Test desc one
5     exec:
6       command: echo "Hello World"
7     test:
8       current.stdout == "Hello World"
```
```console
$ go run cmd/runn/main.go run tmp.yml
F
1) tmp.yml 6a5d63a3c2c505fbc67b941937ee79c16113fc0e
Failure/Error: test failed on 'Test desc'.steps.one 'Test desc one': condition is not true
Condition:
current.stdout == "Hello World"
│
├── current.stdout => "Hello World
│   "
└── "Hello World" => "Hello World"
Failure …
```

Fix condition tree to make it easier to read.

---

README.md
capture/runbook.go
capturer.go
cmdout.go
debugger.go
exec.go
exec_test.go
parse.go
testdata/book/exec.yml
testdata/exec.yml.debugger.golden
testdata/exec.yml.runbook.golden
testdata/include_main.yml.runbook.golden

Support `exec.shell:` for specifying the shell to use.
```yaml
- exec:
command: hello 
shell: bash
```

Support `exec.shell:` for specifying the shell to use

---

book.go
cmd/coverage.go
cmd/loadt.go
cmd/run.go
coverage.go
flags/flags.go
operator.go
option.go
path.go

```console
$ runn run *.yml \
--runner req:https://example.test \
--runner req2:https://other.test \
--http-openapi3 req:path/to/openapi3.yaml \
--http-openapi3 req2:path/to/other.yaml
```

Enable to specify OpenAPI3 documents for each HTTP runner.

---

operator_test.go
path.go
path_test.go
testdata/book/include_vars_included.yml
testdata/book/include_vars_main.yml

Error if the file does not exist.

---

id.go
operator.go

The initial ID of the operator is to be a random ID.

Add prefix to random ID to make it clear that it is randomly generated

---

http.go
http_test.go

The domain of a cookie can be either a domain that starts with a dot or a domain that does not start with a dot.
A domain that starts with a dot is limited to the domain and its subdomains.
For example, a cookie set on the domain .github.com will be sent to subdomains such as gist.github.com and api.github.com.
On the other hand, a domain that does not start with a dot is limited to the domain itself.
For example, a cookie set on the domain github.com will only be sent to zenn.dev

Fixed a bug with subdomain enabled cookies

---

cmd/new.go

ref: https://zenn.dev/link/comments/20c5b63af49c08

Implicitly enable scope `run:parent` if `--and-run` is enabled

---

README.md
builtin/pick.go
builtin/pick_test.go
option.go
option_test.go
testdata/book/builtin_pick.yml

This pull request adds `pick()` built-in expr function which is equivalent to the samber/lo's [`PickByKeys()`](https://github.com/samber/lo?tab=readme-ov-file#pickbykeys) function.
```yaml
test: |
compare(
pick({"a": 1, "b": 2, "c": 3}, "a", "c"),
{"a": 1, "c": 3}
)
```
---
FYI: This PR is the 1st one that I implemented today. 
1.  https://github.com/h6ah4i/runn/tree/feature/add-built-in-function-pick 👈  This pull request
2. https://github.com/h6ah4i/runn/tree/feature/add-built-in-function-omit
3. https://github.com/h6ah4i/runn/tree/feature/add-built-in-function-merge
4. https://github.com/h6ah4i/runn/tree/feature/support-yaml-anchor-alias-handling

Introduce pick() expr built-in function

---

README.md
builtin/omit.go
builtin/omit_test.go
option.go
option_test.go
testdata/book/builtin_omit.yml

This pull request adds `omit()` built-in expr function which is equivalent to the samber/lo's [`OmitByKeys()`](https://github.com/samber/lo?tab=readme-ov-file#omitbykeys) function.
```yaml
test: |
compare(
omit({"a": 1, "b": 2, "c": 3}, "b"),
{"a": 1, "c": 3}
)
```
※ I know that the `compare()` function has the same behavior included, but this new function is still useful for composing JSON object in other places.
---
FYI: This PR is the 1st one that I implemented yesterday. 
1.  ~~https://github.com/h6ah4i/runn/tree/feature/add-built-in-function-pick~~ (Thx, already merged :pray:)
2. https://github.com/h6ah4i/runn/tree/feature/add-built-in-function-omit 👈  This pull request
3. https://github.com/h6ah4i/runn/tree/feature/add-built-in-function-merge
4. …

Introduce omit() expr built-in function

---

README.md
builtin/merge.go
builtin/merge_test.go
option.go
option_test.go
testdata/book/builtin_merge.yml

This pull request adds `merge()` built-in expr function which is equivalent to the samber/lo's [`Assign()`](https://github.com/samber/lo?tab=readme-ov-file#assign) function.
```yaml
test: |
compare(
merge({"a": 1, "b": 2}, {"b": 3, "c": 4}),
{"a": 1, "b": 3, "c": 4}
)
```
---
FYI: This PR is the 3rd one that I implemented yesterday. 
1.  ~~https://github.com/h6ah4i/runn/tree/feature/add-built-in-function-pick~~ (Thx, already merged :pray:)
2. ~~https://github.com/h6ah4i/runn/tree/feature/add-built-in-function-omit~~ (Thx, already merged :pray:)
3. https://github.com/h6ah4i/runn/tree/feature/add-built-in-function-merge 👈  This pull request
4. https://github.com/h6ah4i/runn/tree/feature/support-yaml-anchor-alias-handling

Introduce merge() expr built-in function

---

runbook.go
runbook_test.go
testdata/book/single_step.yml
testdata/book/single_step_map.yml
testdata/pick_step.single_step.yml.0.golden
testdata/pick_step.single_step_map.yml.0.golden

I noticed that `detectRunbookAreas()` function fails to parse the `steps` section in a specific situation.
When a runbook only has **single step with map-style**, the step will be parsed as `ast.MappingValueNode` which is not currently handled by runn.

Fix detectRunbookAreas() failure when the runbook has only 1 step in maps format

---

http.go
runbook.go
runbook_test.go
testdata/book/yaml_anchor_alias.yml
testdata/book/yaml_anchor_alias_always_failure.yml
testdata/pick_step.yaml_anchor_alias.yml.0.golden
testdata/pick_step.yaml_anchor_alias.yml.7.golden
testdata/pick_step.yaml_anchor_alias_always_failure.yml.0.golden
testdata/pick_step.yaml_anchor_alias_always_failure.yml.1.golden

This pull request introduces [YAML's anchors & aliases](https://medium.com/codex/yaml-aliases-32a9cc496a28) support in runbooks.
The aliases are very useful if you want to re-use same fields multiple times.
```yaml
my_aliases:
common_request_headers: &common_request_headers
authorization: 'Bearer **********'
accept: 'application/json'
steps:
- req:
/api-foo:
get:
headers:
<<: *common_request_headers
additionnal-header: foo
body:
application/json: null
- req:
/api-bar:
get:
headers:
<<: *common_request_headers
additionnal-header: bar
body:
application/json: null
```
---
FYI: This PR is the 4th one that I implemented yesterday. 
1.  ~~https://github.com/h6ah4i/runn/tree/feature/add-built-in-function-pick~~ (Thx, already merged :pray:)
2. …

Support using YAML's anchors and aliases in runbooks

---

operator.go
result_test.go

Elasped was not recorded in result.json due to an inexplicable Unmarshal.
ref: https://github.com/k1LoW/runn/commit/abc3ac308bf48c39c3dea0e46e48edec14ce4393#diff-5063501a84242fcc60e366cd9998632d2f48cd7838a1c58d6b7167c965986600L1514-R1518

Revert inexplicable Unmarshal

---

runbook.go
runbook_test.go

Change indentation options for flattening Yaml aliases

---

book.go
go.mod
grpc.go
hosts.go
hosts_test.go
operator.go
operator_test.go
runbook.go
testdata/book/cdp_with_host_rules.yml
testdata/book/cdp_with_host_rules_wildcard.yml
testdata/book/grpc_with_host_rules.yml
testdata/book/grpc_with_host_rules_wildcard.yml
testdata/book/http_with_host_rules.yml
testdata/book/http_with_host_rules_wildcard.yml

Allows control of hostname/IP address mapping without modifying /etc/hosts ( like `curl --resolve` ).

Support for `hostRules:` (control of hostname/IP mapping) in HTTP runner, gRPC runner and CDP runner

---

hosts.go

Fix net::ERR_CERT_COMMON_NAME_INVALID error

Use `--host-resolver-rules` instead of `--host-rules` in CDP Runner

---

capture/runbook.go
capturer.go
cmdout.go
cmdout_test.go
debugger.go
operator.go
testdata/runn_cmdout_1.golden
testdata/runn_cmdout_by_step1.golden

Output results step by step when the `--verbose` option is enabled (Update `runn.Capturer` interface)

---

operator.go

Thank you for creating the fantastic tool runn. During usage, I encountered a potential panic scenario. I've addressed this in the attached pull request to contribute to the stability and reliability of runn. I hope this is helpful.
This PR addresses a potential panic issue in the handling of the dump action when the expr field is specified without providing an out field. If the expr field was used in a dump action without an accompanying out, the system would encounter a panic. The issue can be illustrated with the following configuration:
```yaml
desc: "hello world!"
steps:
say_hello:
desc: "echo hello"
exec:
command: echo hello
test:
current.exit_code == 0
dump:
expr: current.stdout
```
```
runn run --scopes run:exec hello.yml
panic: interface conversion: interface {} is nil, not …
```

fix: Fix potential panic

---

operator.go
operator_test.go
testdata/book/dump.yml

Allow no `dump.out:`
```yaml
dump:
expr: vars.some + 'hello'
```

Set default output for Dump runner

---

cdp.go
cdp_test.go

SSIA. And delay the timing of Chrome startup.

 Merge run() function context and runner (chrome) context

---

http.go

Fix `eval error: cannot fetch Value from *http.Cookie`

Record the value of http.Cookie in store, not the pointer to http.Cookie.

---

go.mod
go.sum

SSIA
ref: https://github.com/pb33f/libopenapi-validator/releases/tag/v0.0.46

Update github.com/pb33f/libopenapi-validator to v0.0.46

---

result.go

This is to get an output that is as environmentally independent as possible, similar to id.

Set output path to a path relative to the Git root as possible.

---

http_validator.go
http_validator_test.go

Add workaround for invalid validator instance after validation error. 

---

.github/workflows/ci.yml
coverage.go
http_validator.go
http_validator_test.go
runner_option.go

Fix problem with validators behaving incorrectly when running concurrently

---

coverage.go
http_validator.go
http_validator_test.go
runner_option.go

ref: https://github.com/k1LoW/runn/issues/882#issuecomment-2082602173

Fix test for problem with validators behaving incorrectly when running concurrently

---

eval.go
eval_test.go
exprtrace/eval.go
exprtrace/tree_printer.go

This pull request implements the proposal outlined in issue #803. When the `compare()` built-in function returns `false`, a diff output will automatically be added for convenience.

Print diff info for the compare() built-in function (issue #803)

---

builtin/time.go
builtin/time_test.go

ref: https://github.com/k1LoW/runn/issues/926

Fix `time()` ( allow any type )

---

bind_test.go
db_test.go
exec_test.go
operator.go
operator_test.go
store.go

Use `steps[*].outcome` `steps.<key>.outcome` instead.

Remove `steps[*].run` `steps.<key>.run` from store

---

operator.go
operator_test.go

Fix https://github.com/k1LoW/runn/issues/934
Support following
```
runn run path/to/**/*.yml --label '!foo'
runn run path/to/**/*.yml --label '!foo and !bar'
```

Support negative label condition

---

cmd/run.go
flags/flags.go

Added an option to enable colorized output in non-tty output streams like GitHub Actions. When specifying this option, bypass the check for non-tty output streams by the [fatih/color](https://github.com/fatih/color) package.
Output without option:
```bash
$ runn run testdata/book/runn_0_success.yml | less
.
1 scenario, 0 skipped, 0 failures
```
Output with `--force-color` option:
```bash
$ runn run testdata/book/runn_0_success.yml --force-color | less
[32m.[0m
[32m1 scenario, 0 skipped, 0 failures
[0m
```

Add `--force-color` option for forcing colorized output

---

cdp.go
cdp_test.go
db.go
db_test.go
go.mod
go.sum
grpc.go
grpc_test.go
include.go
integration_test.go
operator.go
operator_test.go
option.go
path.go
ssh.go
testdata/book/db_connection.yml
testdata/book/db_connection_included.yml
testdata/book/db_connection_included_with_new_conn.yml
testdata/book/mysql.yml
testutil/runbook.go

Add a cleanup operation because connections were left behind when defining a DB/gRPC/SSH/CDP Runner in Include runner.

---

README.md
book.go
operator.go
operator_test.go
runner_runner.go
runner_runner_test.go
step.go
testdata/book/runner_runner.yml

```yaml
desc: Test with Runner runner
steps:
-
exec:
command: somecommand
-
runner:
db:
dsn: ${{ previous.stdout }}
-
db:
query: SELECT * FROM users;
test: 'current.rows[0].username == "alice"'
```

Add "Runner runner" that allows runners to be defined in the middle of steps.

---

cmdout.go
cmdout_test.go
include.go
operator.go
operator_test.go
result.go
result_test.go
step.go
testdata/book/needs_3.yml
testdata/book/needs_4.yml
testdata/book/needs_5.yml
testdata/result_out_json_3.golden

Previously, when the needs: section was specified in the included runbook, execution was blocked in some cases.
This fix resolves the needs: section of the included runbook.
This resulted in the Include runner running multiple runbooks. So we also modified the structure of the results.

Support for the combined use of Include Runner and `needs:`

---

include.go
operator.go
operator_test.go
testdata/book/needs_3.yml
testdata/book/needs_4.yml

Propagate runn.kv / add tests

---

runbook.go

Resolves #1009 
```sh
$ go run ./cmd/runn/main.go new -- grpcurl -plaintext localhost:8080 myApp.MyService/Health
runners:
greq: grpc://localhost:8080
steps:
- greq:
myApp.MyService/Health: {}
```
```sh
$ go run ./cmd/runn/main.go new -- grpcurl -plaintext localhost:8080 myApp.MyService/Health
runners:
greq: grpc://localhost:8080
steps:
- greq:
myApp.MyService/Health:
message: {}
```
When I ran `go run cmd/runn/main.go new --and-run --grpc-no-tls -- grpcurl -plaintext localhost:8080 myApp.myService/Health`, the output was like this.
```yaml
runners:
greq: grpc://localhost:8080
steps:
- greq:
myApp.myService/Health: {}
test: |
current.res.headers["content-type"][0] == "application/grpc"
&& …
```

Fix the output of `runn new` for a gRPC method which needs a empty message

---

cmd/run.go
result.go
result_test.go
testdata/result_out_0.golden
testdata/result_out_1.golden
testdata/result_out_2.golden

SSIA.
ref: https://zenn.dev/link/comments/7054a8d20effdf

If there are runbook run failures in `runn run`, list the failure results at the end (always).

---

README.md
cdp_test.go
go.mod
go.sum
http_validator.go
operator_test.go
option.go
runner_option.go
testdata/book/http_circular_refs.yml
testdata/openapi3-circular-references.yml
testutil/http.go

Fix https://github.com/k1LoW/runn/issues/1026

Add `skipCircularReferenceCheck` for skipping circular reference check in the OpenAPI3 document.

---

Makefile
loadt.go
loadt_test.go
operator.go
operator_test.go
testdata/book/http_sleep.yml

SSIA.
ref: https://zenn.dev/link/comments/44caa6d577cd0f

Once a scenario is run, it is run to the end ( `runn loadt` ).

---

flags/flags.go
operator.go
operator_test.go

Fix https://github.com/k1LoW/runn/issues/1032
- [Set --fail-fast value to operators](https://github.com/k1LoW/runn/pull/1040/commits/78f94f7d0957f459dbe173d7d4c2629504327272)
- [If it was cancelled, mark it as skipped.](https://github.com/k1LoW/runn/pull/1040/commits/7d691ac088bc669cabe203830dd89270284b60df)

Fix `--fail-fast`

---

operator.go

Fix handle err of operators on Run/RunN

---

builtin/compare.go
builtin/compare_test.go
builtin/diff.go
builtin/diff_test.go
builtin/faker.go
builtin/merge.go
builtin/merge_test.go
builtin/omit.go
builtin/omit_test.go
builtin/pick.go
builtin/pick_test.go
builtin/time.go
builtin/time_test.go
builtin/url.go
eval.go
option.go

Remove `panic()` from `builtin` functions

---

book.go
builtin/compare.go
builtin/compare_test.go
builtin/diff.go
builtin/diff_test.go
eval.go
internal/deprecation/warning.go
operator.go
option_test.go
parse.go
runner_option.go
testdata/book/builtin_compare.yml

ref: https://github.com/k1LoW/runn/issues/1047
Because variadic arguments like Go cannot be used in expr-lang.
While accepting both arguments, deprecate the variadic argument type.

Update signature of compare/diff built-in functions step by step

---

README.md
book.go
debugger_test.go
dump.go
dump_test.go
exec.go
exec_test.go
go.mod
go.sum
operator.go
operator_test.go
option.go
store.go
testdata/book/with_secrets.yml
testdata/with_secrets.yml.debugger.golden

ref: #986 
By listing the names of variables stored in the secrets section, you can mask all the values of those variables in the output.
```console
$ cat testdata/book/with_secrets.yml
desc: With secrets
debug: true
vars:
message: hello
secrets:
- vars.message
steps:
-
desc: 'Print "hello world!!"'
exec:
command: echo hello world!!
-
desc: 'Print "hello world!!" again'
exec:
command: cat
stdin: '{{ steps[0].stdout }}'
-
desc: 'Check result of previous command contains "hello"'
test: 'steps[1].stdout contains "hello"'
$ go run cmd/runn/main.go run testdata/book/with_secrets.yml --scopes run:exec
Run "Print \"***** world!!\"" on "With secrets".steps[0]
-----START COMMAND-----
echo ***** world!!
-----END COMMAND-----
-----START STDOUT-----
***** world!!
-----END STDOUT-----
-----START …
```

Implement `secrets:` section

---

book.go
cache.go
cdp.go
coverage_test.go
debugger_test.go
hosts_test.go
http.go
include.go
operator.go
operator_test.go
option.go
path.go
path_test.go
runbook.go

ref: #1073 
Enhanced scope determination for file paths containing runbooks.
In addition, absolute paths are now allowed everywhere.
It's a bug that in some sections it was reading files in directories higher than the runbook even though there was no `read:parent` scope.

Allow absolute paths and enhance scopes detection

---

operator.go
operator_test.go
testdata/book/include_a.yml

Even if `SkipIncluded` is enabled, if the including runbook is not in the list of runs, the included runbook should be run.

Fix SkipIncluded

---

cdp.go

ref: https://github.com/k1LoW/runn/actions/runs/12305651399/job/34345712253?pr=1111

Fix race condition in cdp.go

---

capture/runbook.go
grpc.go
http.go
include_test.go
operator.go
parse.go
testutil/grpc.go
testutil/port.go

Fix lint warn

---

cmd/new.go
cmdout.go
go.mod
result.go
runbook.go
store.go
test.go

Fix new command.

---

bind.go
bind_test.go
cdp.go
cdp_test.go
db.go
db_test.go
dump.go
dump_test.go
exec.go
exec_test.go
grpc.go
grpc_test.go
http.go
http_test.go
include.go
include_test.go
operator.go
operator_test.go
runner_runner.go
ssh.go
store.go
store_test.go
test.go
test_test.go

This will allow for easier handling of defer.
ref: https://github.com/k1LoW/runn/pull/1119

Change the method of holding the list type step in store from slice to map.

---

README.md
bind.go
cdp.go
db.go
dbg.go
defer.go
defer_test.go
docs/designs/defer.md
dump.go
exec.go
grpc.go
http.go
include.go
operator.go
operator_test.go
parse.go
parse_test.go
runner_runner.go
ssh.go
step.go
store.go
test.go
testdata/book/custom_runner_http.yml
testdata/book/defer.yml
testdata/book/defer_included.yml
testdata/book/defer_map.yml

Support `defer:` for deferring steps in a runbook.

Support `steps[*].defer:` `steps.<key>.defer:` for deferring steps in a runbook

---

README.md
force.go
force_test.go
operator.go
step.go
testdata/book/force_step.yml

Support `steps[*].force:` `steps.<key>.force:` for running step forcefully

---

store.go
store_test.go

Do not include `runn.*` in the include runner store.

---

README.md

This link is referenced in here: https://github.com/expr-lang/expr/tree/master#documentation

docs: Updated the link to the `expr` Language Definition with a richer one

---

store.go
testdata/book/loop.yml

Fix: https://github.com/k1LoW/runn/issues/1128

Fix a bug that caused store values to be lost when using `loop:`.

---

alias.go
internal/eval/eval.go
internal/eval/eval_test.go

Move eval to internal/eval

---

cmd/loadt.go

Currently at `runn loadt` cmd, the existing error (`err`) was overwritten by the new error returned from `runn.RemoveCacheDir()`. This change uses `errors.Join(err, ...)` to merge both errors and ensure the original context is not lost.
By this bug, even if the condition of `--threshold` flag does not meets, no error was returned (exit with 0).
before
```console
$ go run cmd/runn/main.go loadt --env-file load_test/.env load_test/main.yaml --duration 1s --warm-up 0s --threshold 'total > 10'
Number of runbooks per RunN....: 1
Warm up time (--warm-up).......: 0s
Duration (--duration)..........: 1s
Concurrent (--load-concurrent).: 1
Max RunN per second (--max-rps): 1
Total..........................: 2
Succeeded......................: 2
Failed.........................: 0
Error …
```

fix(loadt): Fix a bug that overwrote the original error

---

operator.go
testdata/book/loop.yml

Fix: https://github.com/k1LoW/runn/issues/1144

If loop.count <= 0, skip step.

---

Makefile
cmd/loadt.go

Fix loadt stucked

---

.github/workflows/ci.yml

ref: https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md

fix: Disable apparmor_restrict_unprivileged_userns on CI

---

book.go

This PR fixes an issue where `defer` and `force` options could not be used in combination with other runners. 
Currently, the validation incorrectly rejects valid configurations that should be supported according to the documentation.
The following valid configuration results in a validation error:
```yaml
desc: Test for defer
steps:
- desc: step 1
test: len(steps) == 0
- defer: true
desc: defererd step a
test: true
exec:
command: echo "deferred step a"
```
Error message:
```bash
./runn run testdata/book/defer.yml --debug --scopes run:exec                                                                                                                                                                                                             6s
Error: failed to load runbook …
```

fix: Added support for using defer and force options with other runners.

---

.github/workflows/release-test.yml
Dockerfile
Dockerfile.slim

ci(workflow): add release test workflow for Docker images

---

runbook.go

In some cases, the parser registers more rows for the test than it actually occupies. Because of this, if this test is the last one in the file, runn crashes completely without displaying the test results.
This problem is most serious when splitting tests into different files (include), because one file causes all subsequent tests to crash.
Instead of outputting an error about “line not found”, assign the end of the test to the end of the file.

fix: line not found

---

operator.go
operator_test.go

Fix https://github.com/k1LoW/runn/issues/1207

fix: fix a bug that caused failure when using `--runner` and `--http-openapi3` together

---

debugger_test.go
include.go
operator_test.go
testdata/book/include_with_secrets.yml
testdata/book/with_secrets.yml
testdata/include_with_secrets.yml.debugger.golden
testdata/with_secrets.yml.debugger.golden

Fix https://github.com/k1LoW/runn/issues/1203

fix: the secrets: section in the included runbook is not working 

---

bind.go
book.go
cdpfn.go
db.go
grpc.go
internal/store/store.go
internal/store/store_test.go
operator.go
operator_test.go
option.go
testutil/db.go
testutil/runbook.go
vars.go
yaml.go

refactor: modernize

---

book.go
cdp.go
cdp_options_test.go
option.go
runner_option.go

Previously, it was not possible to pass launch flags to Chrome (CDP) from book.
This change adds support for specifying and passing these flags, enabling more flexible Chrome configurations.
example:
```yaml
runners:
cc:
addr: chrome://new 
flags:
proxy-server: 127.0.0.1:8080
proxy-bypass-list: <local>,*.google.com
```
I’ve added some basic tests (cdp_options_test.go) that seem to cover the change, but please let me know if more are needed.

Support passing Chrome launch options from book

---

cmd/run.go
internal/flags/flags.go

Thank you for always maintaining this great tool.
This PR closes #762 and adds support for the `--coverage` and `--coverage-out` flags in the `run` command.

Add coverage and coverage-out flags to run command

---

db.go

Hello, thank you for maintaining such a great tool.
Recently, I encountered a situation that I want to handle postgresql `NUMERIC` type column.
This PR will fix this error.
```
Failure/Error: db query failed on "Test fixed-point data types".steps[0]: invalid column: evaluated n_decimal, but got NUMERIC(1234.56789): strconv.Atoi: parsing "1234.56789": invalid syntax
```
Support postgresql `NUMERIC` column type. It also support `DECIMAL`, which is aliased to `NUMERIC`.
`init.sql`
```sql
CREATE TABLE IF NOT EXISTS "runn_test" (
n_decimal DECIMAL(10,5) NOT NULL,
n_numeric NUMERIC(10,5) NOT NULL
);
INSERT INTO "runn_test" (n_decimal, n_numeric) VALUES (1234.56789, 98765.4321);
```
`compose.yml`
```yaml
services:
postgres:
image: postgres:17-alpine
container_name: runn-postgres
environment: …
```

feat: support postgresql numeric column type

---

http.go
operator.go

This pull request improves error handling in the HTTP runner by capturing non-critical errors encountered during response validation and processing, rather than immediately halting execution. These errors are now stored in the step's result for later inspection, making the runner more robust and debuggable.
**Error handling improvements:**
* Introduced a new constant `runnerStoreErrorKey` to store non-critical errors encountered during HTTP request execution.
* Modified the `run` method in `http.go` to collect errors related to unsupported response formats, failed response body reads, and failed JSON unmarshalling into a single `resError` variable instead of returning early.
* Recorded the collected `resError` in the step's result map under the new `runnerStoreErrorKey`, allowing errors …

fix: parsing errors in the response body should not be treated as runner failures.
