grpc.go
grpc_test.go
testdata/grpctest.proto

Support gRPC (Step 1: Server streaming RPC)

---

grpc.go
grpc_test.go
testdata/grpctest.proto

Support gRPC (Step 3: Bidirectional streaming RPC)

---

include.go
include_test.go

refs https://github.com/k1LoW/runn/pull/93
The following syntax will allow json reads
```yml
include:
path: path/to/include.yml
vars:
jsonVar: 'json://path/to/vars.json'
```

Support reading json in the vars section of includes

---

dump.go
include.go
operator.go
operator_test.go
testdata/book/dump.yml

- Fix a case where dump runner could not dump due to the existence of
registered functions.
- Stop recording unnecessary parentVars.

Normalize storing values

---

.golangci.yml
grpc.go
grpc_test.go
parse.go
parse_test.go
testdata/book/grpc.yml

[BREAKING] Fix miss spell

---

dump_test.go
operator.go
store.go

Align with the type and structure of `store.steps`

Change type of store.stepMap

---

test.go
test_test.go

Use parser.Parse() instead of own parser

---

testdata/book/httpbin.yml
testdata/book/httpbin_include.yml

Append current test.

---

db.go

refs https://github.com/k1LoW/runn/issues/124
I could not reproduce the error in the test code using sqlite, so I would like to detail the error and check the contents.

More detailed error messages when retrieving columns

---

include.go
include_test.go
testdata/book/multiple_include_a.yml
testdata/book/multiple_include_b.yml
testdata/book/multiple_include_main.yml

Expand vars of Include while preserving type information

---

eval.go
eval_test.go
include_test.go
testdata/book/multiple_include_a.yml
testdata/book/multiple_include_b.yml
testdata/book/multiple_include_main.yml

ref: #99
Thanks to the improvements at https://github.com/k1LoW/runn/pull/140 we can turn this workaround off!

Revert 'Allow strings "true" and "false" as true/false'

---

.octocov.yml
capture/runbook.go
capture/runbook_test.go
capturer.go
db.go
debugger.go
go.mod
grpc.go
grpc_test.go
http.go
operator.go
option.go
parse.go
parse_test.go
test.go
test_test.go
testdata/book/http.yml
testdata/book/initdb.yml
testdata/db.yml.debugger.golden
testdata/db.yml.runbook.golden
testdata/exec.yml.runbook.golden
testdata/grpc.yml.runbook.golden
testdata/http.yml.debugger.golden
testdata/http.yml.runbook.golden
testutil/db.go
testutil/dir.go
testutil/grpc.go
testutil/http.go

ref: https://github.com/k1LoW/runn/issues/116#issuecomment-1244865698
- Add built-in capturer `capture.Runbook`
- Change `Capturer interface`
- Fix built-in function `compare()` for comparison with struct written directly in the expression.

Introduce built-in capturer `capture.Runbook`

---

cmd/run.go

Add option `--capture`

---

book.go
include.go
include_test.go
operator.go
operator_test.go
option.go
testdata/book/httpbin.yml
testdata/book/vars_external.yml
vars.go
vars_test.go

Relative paths to json reads

---

bind.go
bind_test.go

Append reserved key
* included
* current
* i

Fix bind reserved key

---

loop.go
parse.go
parse_test.go

Decimal point was not considered in the parsing of duration.

Decimal point was not considered in the parsing of duration.

---

operator.go
option.go
testdata/book/httpbin.yml
testdata/book/httpbin_include.yml

Fix error handling

---

book.go
operator_test.go
testdata/book/github_map.yml
testdata/book/http.yml
testdata/openapi3.yml

Fix book path

---

cmd/run.go
option.go
option_test.go
testdata/book/lay_0.yml
testdata/book/lay_1.yml
testdata/book/lay_2.yml

ref: #145 
Support `--overlay/--underlay` option for CLI and `Overlay/Underlay` option for test helper.

Support `--overlay/--underlay` option for CLI and `Overlay/Underlay` option for test helper

---

.github/workflows/tagpr.yml

Re-fix release pipeline

---

README.md

Add doc about structure of request and response

---

operator.go

Show number of loop times when an error occurs during loop.

---

option.go
option_test.go

I really wanted to test the built-in functions by themselves, but it was difficult, so I committed only the intermediate tests.
Can I define the built-in functions by themselves?
I want to check the behavior of the compare function.

Fixed compare function always returning true

---

test.go
test_test.go
testdata/book/httpbin.yml

refs https://github.com/k1LoW/runn/issues/123

Support for comment statements within the test syntax

---

bind.go
dump.go
eval.go
include.go
operator.go
test.go

Wrap expr.Eval() with eval()

---

eval.go
eval_test.go

Fix timing of trimming comments of string to eval()

---

eval.go
operator.go

Move logic form o.expand() to evalExpand()

---

README.md
book.go
http.go
http_test.go
operator_test.go
option.go
option_test.go
runner_option.go
testdata/book/http.yml
testdata/book/http_not_follow_redirect.yml
testdata/http.yml.debugger.golden
testdata/http.yml.runbook.golden
testdata/openapi3.yml
testutil/http.go

Add `notFollowRedirect` option for HTTP Runner

---

capture/runbook.go
capturer.go
debugger.go
operator.go

ref: #204
Successes, failures, and skips in runbook runs should also be captured.

Append capture points

---

operator.go
operator_test.go
testdata/book/runn_0_success.yml
testdata/book/runn_1_fail.yml
testdata/book/runn_2_success.yml
testdata/book/runn_3.skip.yml

Make it possible to get counts of run results

---

capture/runbook.go
capturer.go
cmd/run.go
cmdout.go
debugger.go
operator.go
option.go
path.go
path_test.go

[BREAKING] Change the custom operation of `runn run` command to `operators.RunN()`

---

cmd/new.go

```console
$ cat testdata/curls.txt
curl https://httpbin.org/json
curl https://httpbin.org/xml
$ cat testdata/curls.txt | runn new --and-run
runners:
req: https://httpbin.org
steps:
- req:
/json:
get:
body: null
test: |
current.res.status == 200
&& current.res.headers['Access-Control-Allow-Credentials'][0] == "true"
&& current.res.headers['Access-Control-Allow-Origin'][0] == "*"
&& current.res.headers['Content-Length'][0] == "429"
&& current.res.headers['Content-Type'][0] == "application/json"
&& 'Date' in current.res.headers
&& current.res.headers['Server'][0] == "gunicorn/19.9.0"
&& compare(current.res.body, {"slideshow":{"author":"Yours Truly","date":"date of publication","slides":[{"title":"Wake up to WonderWidgets!","type":"all"},{"items":["Why …
```

Support `runn new` via STDIN

---

bind.go
bind_test.go
operator.go
operator_test.go
store.go
test.go
test_test.go
testdata/book/previous.yml

Support `previous` variable

---

README.md
cdp.go
cdp_test.go
cdpfn.go
debugger_test.go
integration_test.go
parse.go
testdata/book/cdp.yml
testdata/book/pkg_go_dev.yml
testdata/cdp.yml.debugger.golden
testdata/http.yml.debugger.golden
testdata/http.yml.runbook.golden
testdata/pkg_go_dev.yml.debugger.golden
testutil/http.go
yaml.go

Add `setUploadFile` for uploading file via browser.

---

book.go
operator.go
operator_test.go
option.go
result.go

Make AfterFuncs receive runbook run result ( contains error )

---

cdp.go
cdp_test.go

ref: https://github.com/k1LoW/runn/pull/283

Set timeout to CDP Runner for each step

---

README.md
option.go
option_test.go

base64encode & decode as built-in func

---

README.md
cdp_test.go
cdpfn.go
testutil/http.go

access to localStorage and sessionStorage.
This enables you
- check storage state
- get data in localStorage or sessionStorage which is difficult to produce via http, for example authentication sdk output
```
// add debug log
for _, v := range resp {
log.Println("localStorage: len: %d, item: %v", len(v), v)
if len(v) != 2 {
continue
}
m[v[0]] = v[1]
}
```
```
//workbook.yml
desc: Browser Storage
runners:
cc: chrome://new
steps:
google:
cc:
actions:
- navigate: https://www.google.com/
- localStorage:
origin: https://www.google.com
- sessionStorage:
origin: https://www.google.com
```
```
$ runn run workbook.yml --debug
Run 'cc' on 'Browser Storage'.steps.google
>>>>>START CDP>>>>>
-----START CDP ACTION-----
name: navigate
args:
url: "https://www.google.com/"
-----END CDP ACTION----- …
```

Add `localStorage` `sessionStorage` to cdpfn

---

http.go

Reset headers as well

---

http.go
http_test.go
testdata/book/http_multipart.yml
testdata/http_multipart.yml.runbook.golden

close: #310 
Eventually, I support map and array so keeping backward compatibility.

Support array for multipart body

---

testdata/book/http_multipart.yml
testdata/http_multipart.yml.runbook.golden
yaml.go

Fix https://github.com/k1LoW/runn/pull/332#discussion_r1035464858

Support capturing multiple files (capture.runbook)

---

README.md
examples/README.md
examples/cdp.yml
examples/expr.yml
examples/func.yml
examples/go-test/book.yml
examples/go-test/main.go
examples/go-test/main_test.go
examples/http.yml
examples/include.yml

refer: #344 
this is my image. If this differs from what you think, please give me feedback.

runn examples

---

vars.go

ref: https://github.com/k1LoW/runn/pull/357

Support fetch files when using external vars with `http://` or `github://`

---

cdpfn.go

refs https://github.com/k1LoW/runn/pull/379#issuecomment-1399414226
refs https://github.com/chromedp/chromedp/issues/1233

Fixing `Frame not found for the given storage id`

---

.github/release.yml

see https://docs.github.com/ja/repositories/releasing-projects-on-github/automatically-generated-release-notes#example-configurations

Specify the Category of the release note

---

cmd/loadt.go
eval.go
eval_test.go
go.mod
loadt.go
loadt_test.go

Fix #387 
Freeze the result received so that they do not change.

Freeze loadt result

---

dump.go
dump_test.go

Support expand vars to output path of dump

---

http.go

Fix https://github.com/k1LoW/runn/issues/393#issuecomment-1420098099

Fix nil pointer dereference at httpRunner

---

integration_test.go
operator_test.go
testdata/book/sshd_local_forward.yml
testutil/container.go

Add SSH port fowarding test ( `local -> SSH port fowarding -> MySQL` )

Add SSH port fowarding test

---

db.go
testdata/book/sshd_local_forward.yml

Fix to be able to parse different return value of query in case of SSH port forwarding

---

README.md
option.go
option_test.go

The following functions are now built-in
https://pkg.go.dev/path/filepath#Base

Append basename function

---

ssh.go

If `keyboardInteractive:` is not set and the user is prompted for key input, runn will prompt the user for input.

If `keyboardInteractive:` is not set and the user is prompted for key input, runn will prompt the user for input.

---

testdata/book/sshd_keep_session.yml

Fix https://github.com/k1LoW/runn/actions/runs/4334862039/jobs/7569038800

Add `interval:` to sshd_keep_session.yml

---

testdata/book/sshd_keep_session.yml
testdata/sshd/entrypoint.d/sudo.sh

Add sudo test using `keepSession: true`

---

operator.go
operator_test.go
result.go
step.go
testdata/book/always_failure.yml
testdata/book/always_success.yml

Record step result for next features

Record step result

---

README.md

Thank you for approving https://github.com/k1LoW/runn/pull/482.
Sorry but I forgot to fix the Spanner DNS setting in the README.md.

Fix `README.md` for spanner

---

cmd/run.go
cmdout.go
result.go
result_test.go
testdata/result_out_0.golden
testdata/result_out_1.golden
testdata/result_out_3.golden

```console
$ runn run ./testdata/book/runn_*.yml
.F.S
1) t/b/runn_1_fail.yml
Failure/Error: test failed on 'Test for RunN (1)'.steps[0]: (false) is not true
false
└── false => false
4 scenarios, 1 skipped, 1 failure
exit status 1
$ runn run ./testdata/book/runn_*.yml --verbose
=== Test for RunN (0) (t/b/runn_0_success.yml) ... ok
--- (0) ... ok
=== Test for RunN (1) (t/b/runn_1_fail.yml) ... fail
--- (0) ... fail
Failure/Error: (false) is not true
false
└── false => false
=== Test for RunN (2) (t/b/runn_2_success.yml) ... ok
--- (0) ... ok
=== Test for RunN (3) (t/b/runn_3.skip.yml) ... skip
--- (0) ... skip
4 scenarios, 1 skipped, 1 failure
exit status 1
```

Further fix output of `runn run`

---

db.go
db_test.go

Thank you for the great tool.
In my project, I am using PostgreSQL's JSONB column. I would love to use this tool for testing, but it doesn't handle JSONB columns well. So I made some modifications on my own. What do you think?
I feel like there is some repetition in the code for supporting JSONB and sqlite's JSON support. Do you have any good ideas? Or do you think it's fine as it is?

Support for JSON type columns

---

testdata/vars.yaml
vars.go
vars_test.go

I would like to load YAML files instead of JSON in the case when we have bulk structured data.

Support yaml:// scheme for vars

---

.golangci.yml
http_validator.go
operator.go
yaml.go

https://github.com/polyfloyd/go-errorlint

Enable errorlint

---

grpc.go

- UseEnumNumbers: true
- EmitUnpopulated: true

Fix for marshaling gRPC responses.

---

.github/workflows/ci.yml
Makefile
README.md
book.go
http.go
operator_test.go
option.go
runner_option.go
testdata/book/sshd_local_forward.yml

Add `skipVerify:` section / HTTPSkipVerify option for HTTP Runner

---

http_validator.go

Friendly find route error message.

---

README.md
builtin/json.go
operator_test.go
option.go
testdata/book/builtin-json.yml
testdata/book/sshd_local_forward_with_openapi3.yml

Add built-in functions for JSON.

---

.goreleaser.yml

- Add Linux arm64 binary
- Add LICENSE to release assets

Fix build settings for release

---

book.go
cdpfn.go
include.go
option.go
path.go

- Use readFile instead of os.ReadFile
- Remove fetchFile

Fix path.go

---

http.go
http_test.go

Fix https://github.com/k1LoW/runn/issues/552

Fix a bug that prevented requests with multipart/form-data when the value is numeric

---

operator.go
store.go

Fix values of stepMapKeys that were not being deleted in the loop.

---

capture/runbook.go
capturer.go
cmd/rprof.go
cmdout.go
debugger.go
operator.go
step.go
trail.go

ID is newly created according to https://github.com/k1LoW/runn/blob/main/docs/designs/id.md

Rename ID to Trail

---

id.go
id_test.go
operator.go

ref: https://github.com/k1LoW/runn/blob/main/docs/designs/id.md

Generate IDs using file path of runbooks.

---

book.go
cmd/run.go
flags/flags.go
operator.go
operator_test.go
option.go

ref: https://github.com/k1LoW/runn/blob/main/docs/designs/id.md

Add methods to specify runbook ID

---

operator.go

- Remove desc, because is is displayed when test fails.
- Add ID for re-run.

In runn as Go package, change the test name for each of the runbooks when they are run.

---

bind.go
bind_test.go
eval.go
operator.go
step.go
testdata/book/dump.yml
testdata/book/include_a.yml
testdata/book/include_main.yml

The previous bind runner could only bind variables or string or int or float but now supports all types.

Bind runner support any type value ( not only string ).

---

color_test.go
runbook.go
runbook_test.go
testdata/pick_step.github.yml.0.golden
testdata/pick_step.github.yml.3.golden
testdata/pick_step.github_map.yml.0.golden
testdata/pick_step.github_map.yml.3.golden
testdata/pick_step.http.yml.0.golden
testdata/pick_step.http.yml.8.golden

Failed to show the step where an error occurred under certain conditions.
Also, no need to expand environment variables

Fix pickStepYAML logic

---

README.md
go.mod
go.sum
option.go
option_test.go

ref: https://github.com/antonmedv/expr/releases/tag/v1.14.0

Bump up expr version to v1.14.0

---

result.go

Enable to get error output for each result

---

capture/runbook_test.go
db.go
integration_test.go
operator.go
option_test.go
testdata/book/db_select.yml
testutil/container.go

ref: #606 
By this Pull Request, DB Runner with DSN disconnects from the database for each scenario.

Fix DB Runner connections are not closed properly

---

integration_test.go
operator.go
operator_test.go
testdata/book/db_select.yml
testdata/book/multiple_conn.yml

Disconnect from gRPC server for each scenario only for gRCP Runner with target.

---

book.go
cmd/coverage.go
cmd/loadt.go
cmd/run.go
flags/flags.go
operator.go
option.go

Add `--http-openapi3` opiton to set the path to the OpenAPI v3 document for all HTTP runners

---

coverage.go

Consider the path of `servers:` in OpenAPI Spec and endpoint of HTTP runners for coverage path resolution.

---

cmd/coverage.go
coverage.go
operator.go

`coverage` command support JSON output

---

cmd/coverage.go

Show total coverage

---

.gostyle.yml
path.go

I thought it would be better to use the standard settings if possible for Go style.
I addressed repetition as the easiest issue to handle.
Are there any other issues that should be addressed with standard settings?

Fix gostyle repetition

---

README.md

`interval` options is not described in README so this PR adds it.

Update README with interval option

---

cmd/coverage.go
testdata/book/cookie_in_requests_automatically.yml

If coverage cannot be collected, report an error.

---

.github/workflows/ci.yml
go.mod

Update toolchain version

---

cmd/coverage.go
operator.go

Sort specs of coverage

---

flags/flags.go
operator.go
option.go

Enable to specify protos for each gRPC runner.

---

README.md
bind.go
bind_test.go
cdp.go
cdp_test.go
db.go
db_test.go
dump.go
dump_test.go
exec.go
exec_test.go
grpc.go
grpc_test.go
http.go
http_test.go
include.go
include_test.go
operator.go
ssh.go
test.go
test_test.go

ref: https://github.com/k1LoW/runn/pull/645
Simplify by having each Runner not have an `*operator` and receive a `*step` each run.

Pass `*step` at the time of running the runner.

---

.golangci.yml
book.go
http.go
http_test.go
integration_test.go
operator.go
option.go
parse.go
parse_test.go
runner_option.go
runner_option_test.go
testdata/book/http_with_use_trace.yml
trace.go

Add header for trace

---

book.go
db.go
db_test.go
include_test.go
operator_test.go
option.go
option_test.go
parse.go
runner_option.go
runner_option_test.go
testdata/book/db.yml
testdata/db.yml.runbook.golden

Add comment to query statement for trace

---

capture/runbook.go
grpc.go
parse.go
testdata/book/grpc.yml
testdata/grpc.yml.debugger.golden
testdata/grpc.yml.runbook.golden

Fix handling of gRPC headers

---

book.go
db_test.go
grpc.go
grpc_test.go
parse.go
runner_option.go

Support header for tracing gRPC requests

---

book.go
db.go
grpc.go
http.go
include.go
operator.go
operator_test.go
option.go
runbook.go
runner_option_test.go

Support `trace:` for tracing

---

README.md
capture/runbook_test.go
debugger_test.go
exec.go
exec_test.go
integration_test.go
operator_test.go
profile_test.go
scope.go
trail.go

Add `run:exec` scope. and deny by default.

---

include.go
include_test.go
path.go

ref: https://github.com/k1LoW/runn/issues/670#issuecomment-1793735534

Fix bug that remote files are not readable in `include.path:`

---

README.md
book.go
cmd/loadt.go
flags/flags.go
include.go
operator.go
option.go
profile_test.go

Profile is turned on by default.

---

book.go
cmd/coverage.go
cmd/list.go
cmd/loadt.go
cmd/run.go
flags/flags.go
operator.go
option.go
option_test.go
vars.go

Support multiple ids specification ( Update `--id` and `RUNN_ID` )

---

operator.go
step.go
trace.go
trail.go
trail_test.go

Integrate runbookID and runbookIDFull

---

flags/flags.go
option.go
option_test.go

Support acceptance of runbook IDs from STDIN

---

book.go
capture/runbook.go
cmd/coverage.go
cmd/list.go
cmd/loadt.go
cmd/run.go
flags/flags.go
operator.go
operator_test.go
option.go
result.go
runbook.go
testdata/book/http.yml
testdata/book/http_multipart.yml
testdata/book/http_not_follow_redirect.yml
testdata/book/http_timeout.yml
testdata/book/http_with_json.yml
testdata/book/http_with_use_trace.yml
testdata/book/httpbin.yml
testdata/book/httpbin_include.yml
testdata/grpc.yml.runbook.golden
testdata/http.yml.runbook.golden
testdata/http_multipart.yml.runbook.golden
testdata/pick_step.http.yml.0.golden
testdata/pick_step.http.yml.8.golden
trail.go

Support `labels:` section in runbooks

---

docs/designs/runbook.md

List the properties of the runbook.

Add design doc for runbook

---

operator.go
operator_test.go

Fix sorting by ids

---

flags/flags.go

The -label option was not enabled.

Fix `--label`

---

runbook.go

Validate runbook `labels:`

---

operator.go
operator_test.go

ref: https://github.com/k2tzumi/runn-action/actions/runs/6850899230/job/18626030732#step:4:96

Allow hyphened labels

---

runbook.go
runbook_test.go

More validate `labels:`

---

operator.go
operator_test.go

ref: https://x.com/katzchum/status/1726201065803248042?s=20

Fix execution timing of functions that retrieve results.

---

http.go
http_test.go

If it is not a file, do not raise an error even if the value is long.

---

bind.go
bind_test.go
dump.go
include.go
loop.go
operator.go
operator_test.go
store.go
test.go

Fix checking reverved store keys

---

bind.go
bind_test.go

ref: https://github.com/k1LoW/runn/issues/569
```yaml
bind:
vars:
"foo[]": current.res
```

Support to bind to slice values

---

bind.go
testdata/book/loop.yml

ref: https://github.com/k1LoW/runn/issues/705#issuecomment-1849242382

Fixe a bug that caused other values to change when bind.

---

flags/flags.go

refs https://github.com/k1LoW/runn/pull/677#pullrequestreview-1798968532

Fix disable profile

---

.github/workflows/benchmark.yml
.github/workflows/ci.yml
.octocov.benchmark.main.yml
.octocov.benchmark.yml
Makefile
benchmark_test.go
go.mod
go.sum
id_test.go
testutil/http.go

Set up benchmark

---

.gitignore
bind.go
debugger.go
runbook.go

Tuning slice/map allocations

---

operator.go

Stop unnecessary pointer passing

---

operator.go

Reduce the number of execution of o.Result()

---

book.go
book_test.go
grpc.go
grpc_test.go
http.go
http_test.go
integration_test.go
operator_test.go
option.go
option_test.go
runner_option.go
runner_option_test.go
testdata/book/http_with_use_trace.yml
testdata/book/http_with_use_trace_header_name.yml
trace.go

Specify the header name for the trace header

---

eval.go
eval_test.go

Fix https://github.com/k1LoW/runn/issues/750

uint64 that came across from the include runner can also be used for loop count.

---

db.go
db_test.go

Fix https://github.com/k1LoW/runn/issues/751

Trim unnecessary CR and LF in queries

---

cmd/loadt.go
cmd/run.go
flags/flags.go
option.go
option_test.go

Add `--host-rules` option to loadt and run commands.

---

book.go
cmd/runn/main.go
db.go
hosts.go
hosts_test.go
integration_test.go
ssh.go
ssh_test.go
testdata/book/sshd_with_host_rules.yml
testdata/book/sshd_with_host_rules_wildcard.yml
testdata/sshd/ssh_config
testutil/ssh.go

Delay connection of DB runner and SSH runner to target as long as possible.

---

integration_test.go
operator.go
operator_test.go
testdata/book/http_skip_validate_request.yml

refs https://zenn.dev/katzumi/scraps/f00a2d3e177b77#comment-36b36b5507b10d

Reflect skipValidateRequest when http-openapi3 option is enabled

---

http_validator.go

refs https://zenn.dev/katzumi/scraps/f00a2d3e177b77#comment-24254b064a4eb5

Keep loaded OpenAPI documents

---

README.md
book.go
go.mod
go.sum
operator.go
runbook.go

Support multiple concurrency keys

---

.github/workflows/benchmark.yml
.github/workflows/ci.yml

Use octocov-action@v1

---

.octocov.benchmark.main.yml
.octocov.benchmark.yml

refs https://github.com/k1LoW/octocov/pull/308

Changed octocov benchmark locale to en for easier viewing of results

---

cmdout.go
cmdout_test.go
testdata/runn_cmdout_by_step2.golden

Fix verbose index

---

book.go
runbook.go
testdata/book/concurrency.yml

Fix concurrency

---

book.go
cmd/loadt.go
cmd/run.go
flags/flags.go
go.mod
go.sum
operator.go
option.go

Set up https://github.com/k1LoW/donegroup for cleanup.

Set up donegroup and timeout for waiting cleanup processes after context canceled

---

README.md

Add link of runn Tutorial

---

.github/dependabot.yml

Ignore github.com/tenntenn/golden

---

bind_test.go
include.go
kv.go
kv_test.go
operator.go
operator_test.go
store.go
store_test.go
testdata/book/kv.yml

This is designed to be a feature in case runn is used as a Go testing package.

Add `runn.kv` for injecting value to running scenarios from external threads.

---

cmdout.go
testdata/runn_cmdout_by_step1.golden

Fix verbose output

---

README.md

Add about logo license

---

book.go
cdp.go
option.go
vars.go
vars_test.go

Fix https://github.com/k1LoW/runn/issues/821

Allow absolute paths with `json://` and `yaml://` in vars

---

go.mod
go.sum

Update go and pkg version

---

dbg.go
store.go

Add `info variables` to the debugger

---

db.go
go.mod
go.sum

Update go-mysql-driver to v1.8.0

---

book.go
hosts_test.go
operator.go
option.go
option_test.go

The host rules specified by the option take precedence.

---

http_validator.go

Set base path for OpenAPI document

---

kv.go
kv_test.go
operator.go

Add ClearKV for clearing the KV store

---

db.go
db_test.go

Fix https://github.com/k1LoW/runn/issues/853

Fix db result handling

---

id.go
operator.go

Set RunResult.Path to a path relative to the Git root as possible.

---

option.go
runner_option.go

Add CDPRunner Option

---

id.go
operator.go

Revert "Set RunResult.Path to a path relative to the Git root as possible."

---

benchmark_test.go
testutil/runbook.go

Add benchmark test with OpenAPI Spec document

---

http_validator.go
http_validator_test.go

Support `nullable: true` in HTTP validator ( Add workaround for libopenapi )

---

http_validator.go

Add lock for globalOpenAPI3DocRegistory

---

include_test.go
store.go
testdata/book/parent_vars_child.yml
testdata/book/parent_vars_parent.yml

parent.vars should not be cleared

---

README.md
go.mod
go.sum
grpc.go

Introduce protoresolv so that protos under it are automatically loaded simply by specifying importPaths.

---

go.mod
testdata/book/grpc.yml
testdata/grpc.yml.coverage.json.golden
testdata/grpc.yml.debugger.golden
testdata/grpc.yml.runbook.golden
testdata/grpctest.proto
testutil/grpc.go

Add test for bytes field

---

eval.go
include_test.go
testdata/book/include_vars_included.yml
testdata/book/include_vars_main.yml

Fix https://github.com/k1LoW/runn/issues/920

Fix a missing line bug when including a multi-line string.

---

operator.go
runner_option.go
warning.go

ref: https://github.com/k1LoW/runn/pull/917#issuecomment-2106413003

Print deprecation warnings

---

go.mod
go.sum
loop.go
operator.go
store.go

Fix to cancel context per runbook execution ( per root loop ) unit.

---

README.md
capture/runbook.go
capture/runbook_test.go
capturer.go
cmdout.go
debugger.go
exec.go
exec_test.go
go.mod
go.sum
parse.go
testdata/book/exec.yml
testdata/exec.yml.debugger.golden
testdata/exec.yml.runbook.golden

Add `exec.background:` for executing commands in the background.

---

cmd/run.go

Support `--format none` to disable output.

---

cmd/coverage.go
cmd/list.go
cmd/loadt.go
cmd/run.go
env.go
env_test.go
flags/flags.go
go.mod
go.sum

Fix https://github.com/k1LoW/runn/issues/941

Support `--env-file` option for loading environment variables from a file.

---

.goreleaser.yml

Use GoReleaser v2

---

README.md
option.go

Improve implementation of the built-in function `select`.

---

step.go
testdata/book/runner_runner.yml

Fix a bug where runners defined in runner runners could not be used in combination with test runner or dump runner.

---

capture/runbook.go
env_test.go
path.go
scripts/fndoc.go
vars_test.go

Fix lint warn

---

runner_runner.go

Fix Runner runner root path

---

cmd/loadt.go
cmd/spinner.go
go.mod
go.sum

Fix loadt output

---

cmdout.go
cmdout_test.go
include.go
operator.go
operator_test.go
result.go
result_test.go
step.go
testdata/book/needs_3.yml
testdata/book/needs_4.yml
testdata/book/needs_5.yml
testdata/result_out_json_3.golden

Support for the combined use of Include Runner and `needs:`

---

.github/workflows/ci.yml
go.mod

Fix https://github.com/k1LoW/runn/issues/980

Set oldstable

---

loadt.go

ref: https://zenn.dev/link/comments/4ffb13a29c051d

Fix latency unit

---

flags/flags.go

Update comment for `--load-concurrent`

---

dbg.go
id.go
id_test.go
include.go
operator.go
operator_test.go

Because `runn.operator` and `runn.operators` exist separately and `[]*runn.operator` is also present, it is difficult to understand.

Rename `runn.operators` to `runn.operatorN`

---

docs/designs/operator.md

Add doc about operator

---

README.md
exec.go
parse.go
testdata/book/exec.yml
testdata/exec.yml.debugger.golden
testdata/exec.yml.runbook.golden

refs https://github.com/k1LoW/runn/issues/620

Live output support for exec runner

---

path.go

Fix remote fetch (Support for other directories of remote files)

---

eval.go

Use math.MaxInt instead

---

path.go

Fix hasRemotePrefix ( add prefixGist )

---

include.go
path.go
path_test.go
testdata/book/http.yml
testdata/book/include_main.yml
testdata/http.yml.runbook.golden

Support `file://` scheme.

---

http.go
http_test.go

Make it possible to explicitly specify files in multipart/form-data requests in the HTTP runner

---

go.mod
go.sum
testdata/pick_step.single_step_map.yml.0.golden

Update goccy/go-yaml to v1.15.2 and go directive version

---

README.md
exec.go
exec_test.go
testdata/exec.yml.runbook.golden
testdata/include_main.yml.runbook.golden

Also allow shell options to be changed ( ref: #1093 ).
Shell options are referenced from [GitHub Actions](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell).

Change the default shell (`sh` -> `bash`) and shell options for the Exec runner.

---

alias.go
book.go
dbg.go
dump.go
internal/expr/expr.go
internal/expr/expr_test.go
internal/store/store.go
loadt.go
operator.go
operator_test.go
option.go
test.go

Rename internal/eval to internal/expr

---

bind_test.go
dump_test.go
include_test.go
internal/store/store.go
internal/store/store_test.go
operator.go

Refactor internal/store

---

go.mod

chore: Bump up go directive version

---

.github/dependabot.yml
go.mod

chore: chore(dependabot): update Go version and remove ignored dependencies

---

testutil/container.go

chore: Use mirror.gcr.io

---

.golangci.yml

chore(ci): golangci-lint migrate

---

db.go
examples/go-test/main.go
http_validator.go
internal/builtin/diff.go
internal/flags/flags.go
operator.go
operator_test.go
parse.go
path.go
testutil/http.go

fix: lint warn

---

coverage.go
coverage_test.go
testdata/book/grpc_without_proto.yml
testdata/grpc_without_proto.yml.coverage.json.golden

Fix https://github.com/k1LoW/runn/issues/1202

feat(coverage): enhance gRPC coverage collection

---

README.md
book.go
book_test.go
include.go
internal/builtin/file.go
internal/builtin/file_test.go
internal/fs/fs.go
operator.go
operator_test.go
option.go
option_test.go
testdata/book/builtin_file.yml
testdata/book/include/builtin_file_included.yml

Fix: https://github.com/k1LoW/runn/issues/1208
Add built-in `file()` function.
`file()` reads the file as a string. Returns nil if it does not exist.
See https://github.com/k1LoW/runn/blob/036cab8243f47387ec626b4aa5eaac5f07726fff/testdata/book/builtin_file.yml
This pull request introduces a new `file` built-in function for reading files as strings, along with related refactoring and enhancements to the codebase. The changes also include improvements to error handling for unsupported file schemes and updates to testing for built-in functions.
* Added a `file` built-in function to read files as strings, returning `nil` if the file does not exist. This includes a new implementation in `internal/builtin/file.go` and corresponding tests in `internal/builtin/file_test.go`. …

feat: add built-in `file()`

---

vars.go
vars_test.go

Support `file://` scheme in `vars:` section.

feat(vars): add support for file scheme evaluation

---

alias.go

Fix https://github.com/k1LoW/runn/issues/1242

fix: expose scope constants for alias

---

README.md

chore: add DeepWiki badge for auto-refresh weekly

---

Makefile

test: add check license using go-licenses
